import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'
import { users, quotes } from './schema'
import { clients, leads } from './schema-leads'

export const workOrderLevelEnum = pgEnum('work_order_level', ['low', 'medium', 'high'])
export const workOrderItemLabelStatusEnum = pgEnum('work_order_item_label_status', [
  'pending',
  'generated',
  'manual',
  'failed',
  'source_changed',
])

export const workOrderInstallers = pgTable('work_order_installers', {
  id: uuid('id').primaryKey().defaultRandom(),
  displayName: text('display_name').notNull(),
  normalizedName: text('normalized_name').notNull(),
  servicem8StaffUuid: text('servicem8_staff_uuid'),
  isActive: boolean('is_active').default(true).notNull(),
  createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('work_order_installers_normalized_name_uq').on(table.normalizedName),
  index('work_order_installers_active_idx').on(table.isActive),
])

export const workOrderStageOptions = pgTable('work_order_stage_options', {
  id: uuid('id').primaryKey().defaultRandom(),
  displayName: text('display_name').notNull(),
  normalizedName: text('normalized_name').notNull(),
  sortOrder: integer('sort_order').default(0).notNull(),
  isActive: boolean('is_active').default(true).notNull(),
  createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('work_order_stage_options_normalized_name_uq').on(table.normalizedName),
  index('work_order_stage_options_active_idx').on(table.isActive),
])

export const workOrderHardwareStatusOptions = pgTable('work_order_hardware_status_options', {
  id: uuid('id').primaryKey().defaultRandom(),
  displayName: text('display_name').notNull(),
  normalizedName: text('normalized_name').notNull(),
  sortOrder: integer('sort_order').default(0).notNull(),
  isActive: boolean('is_active').default(true).notNull(),
  createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('work_order_hardware_status_options_normalized_name_uq').on(table.normalizedName),
  index('work_order_hardware_status_options_active_idx').on(table.isActive),
])

export const workOrders = pgTable('work_orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  identityKind: text('identity_kind').notNull(),
  identityValue: text('identity_value').notNull(),
  servicem8JobUuid: text('servicem8_job_uuid'),
  servicem8CompanyUuid: text('servicem8_company_uuid'),
  servicem8Status: text('servicem8_status').notNull(),
  servicem8Active: boolean('servicem8_active').default(true).notNull(),
  isCurrent: boolean('is_current').default(true).notNull(),
  jobNumber: text('job_number'),
  jobAddress: text('job_address'),
  jobDescription: text('job_description'),
  approximateDescription: text('approximate_description'),
  systemName: text('system_name'),
  length: text('length'),
  color: text('color'),
  itemsServices: text('items_services'),
  glassStatus: text('glass_status'),
  designStatus: text('design_status'),
  siteCondition: text('site_condition'),
  remarks: text('remarks'),
  rawServiceM8Snapshot: jsonb('raw_servicem8_snapshot'),
  clientId: uuid('client_id').references(() => clients.id, { onDelete: 'set null' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  quoteId: uuid('quote_id').references(() => quotes.id, { onDelete: 'set null' }),
  clientName: text('client_name').notNull(),
  companyName: text('company_name'),
  leadScore: integer('lead_score'),
  installerId: uuid('installer_id').references(() => workOrderInstallers.id, { onDelete: 'set null' }),
  stageOptionId: uuid('stage_option_id').references(() => workOrderStageOptions.id, { onDelete: 'set null' }),
  hardwareStatusOptionId: uuid('hardware_status_option_id').references(() => workOrderHardwareStatusOptions.id, { onDelete: 'set null' }),
  maintenanceProgram: boolean('maintenance_program').default(false).notNull(),
  installDate: date('install_date'),
  dateCompleted: date('date_completed'),
  aiRiskLevel: workOrderLevelEnum('ai_risk_level'),
  riskLevelOverride: workOrderLevelEnum('risk_level_override'),
  aiImportance: workOrderLevelEnum('ai_importance'),
  importanceOverride: workOrderLevelEnum('importance_override'),
  aiSuggestion: text('ai_suggestion'),
  aiSuggestionAt: timestamp('ai_suggestion_at', { withTimezone: true }),
  clientContextSummary: text('client_context_summary'),
  clientContextSummaryAt: timestamp('client_context_summary_at', { withTimezone: true }),
  clientApproachNote: text('client_approach_note'),
  lastServiceM8SyncedAt: timestamp('last_servicem8_synced_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex('work_orders_identity_uq').on(table.identityKind, table.identityValue),
  index('work_orders_servicem8_job_uuid_idx').on(table.servicem8JobUuid),
  index('work_orders_status_idx').on(table.servicem8Status, table.servicem8Active, table.isCurrent),
  index('work_orders_job_number_idx').on(table.jobNumber),
  index('work_orders_client_idx').on(table.clientId),
  index('work_orders_lead_idx').on(table.leadId),
  index('work_orders_quote_idx').on(table.quoteId),
])

export const workOrderItems = pgTable('work_order_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  workOrderId: uuid('work_order_id').notNull().references(() => workOrders.id, { onDelete: 'cascade' }),
  servicem8ItemUuid: text('servicem8_item_uuid').notNull(),
  servicem8JobUuid: text('servicem8_job_uuid').notNull(),
  itemCode: text('item_code'),
  quantity: numeric('quantity', { precision: 12, scale: 3 }).notNull(),
  originalDescription: text('original_description').notNull(),
  lineTotalExcludingGst: numeric('line_total_excluding_gst', { precision: 12, scale: 2 }),
  sortOrder: integer('sort_order').default(0).notNull(),
  isActive: boolean('is_active').default(true).notNull(),
  generatedLabel: text('generated_label'),
  manualLabelOverride: text('manual_label_override'),
  labelStatus: workOrderItemLabelStatusEnum('label_status').default('pending').notNull(),
  sourceDescriptionFingerprint: text('source_description_fingerprint'),
  installerId: uuid('installer_id').references(() => workOrderInstallers.id, { onDelete: 'set null' }),
  stageOptionId: uuid('stage_option_id').references(() => workOrderStageOptions.id, { onDelete: 'set null' }),
  hardwareStatusOptionId: uuid('hardware_status_option_id').references(() => workOrderHardwareStatusOptions.id, { onDelete: 'set null' }),
  maintenanceProgram: boolean('maintenance_program').default(false).notNull(),
  installDate: date('install_date'),
  dateCompleted: date('date_completed'),
  aiRiskLevel: workOrderLevelEnum('ai_risk_level'),
  riskLevelOverride: workOrderLevelEnum('risk_level_override'),
  aiImportance: workOrderLevelEnum('ai_importance'),
  importanceOverride: workOrderLevelEnum('importance_override'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex('work_order_items_servicem8_item_uuid_uq').on(table.servicem8ItemUuid),
  index('work_order_items_work_order_active_idx').on(table.workOrderId, table.isActive),
  index('work_order_items_servicem8_job_uuid_idx').on(table.servicem8JobUuid),
])

export const workOrderRefreshRuns = pgTable('work_order_refresh_runs', {
  id: uuid('id').primaryKey().defaultRandom(),
  status: text('status').notNull(),
  syncedCount: integer('synced_count').default(0).notNull(),
  itemSyncedCount: integer('item_synced_count').default(0).notNull(),
  excludedLineCount: integer('excluded_line_count').default(0).notNull(),
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index('work_order_refresh_runs_created_at_idx').on(table.createdAt),
  index('work_order_refresh_runs_status_idx').on(table.status),
])

export const workOrderEvents = pgTable('work_order_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  workOrderId: uuid('work_order_id').notNull().references(() => workOrders.id, { onDelete: 'cascade' }),
  workOrderItemId: uuid('work_order_item_id').references(() => workOrderItems.id, { onDelete: 'set null' }),
  actorId: uuid('actor_id').references(() => users.id, { onDelete: 'set null' }),
  fieldName: text('field_name').notNull(),
  previousValue: jsonb('previous_value'),
  newValue: jsonb('new_value'),
  note: text('note'),
  isClientVisibleCandidate: boolean('is_client_visible_candidate').default(false).notNull(),
  portalTitle: text('portal_title'),
  portalMessage: text('portal_message'),
  portalMarkedBy: uuid('portal_marked_by').references(() => users.id, { onDelete: 'set null' }),
  portalMarkedAt: timestamp('portal_marked_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index('work_order_events_work_order_idx').on(table.workOrderId),
  index('work_order_events_work_order_item_idx').on(table.workOrderItemId),
  index('work_order_events_actor_idx').on(table.actorId),
  index('work_order_events_client_visible_idx').on(table.isClientVisibleCandidate),
  index('work_order_events_created_at_idx').on(table.createdAt),
])
